// theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

export const CHANGE_CATEGORY_MODAL_STATE = 'CHANGE_CATEGORY_MODAL_STATE';
export const CHANGE_SUB_CATEGORY_MODAL_STATE = 'CHANGE_SUB_CATEGORY_MODAL_STATE';
export const CHANGE_BRAND_MODAL_STATE = 'CHANGE_BRAND_MODAL_STATE';

export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY';
export const CHANGE_SELECTED_SUB_CATEGORY = 'CHANGE_SELECTED_SUB_CATEGORY';
export const CHANGE_SELECTED_BRAND = 'CHANGE_SELECTED_BRAND';

export const USER_LOGIN = 'USER_LOGIN';
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN';
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN';

export const USER_DETAILS = 'USER_DETAILS';
export const SUCCESS_USER_DETAILS = 'SUCCESS_USER_DETAILS';
export const ERROR_USER_DETAILS = 'ERROR_USER_DETAILS';

export const GET_CANDIDATES = 'GET_CANDIDATES';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_ERROR = 'GET_CANDIDATES_ERROR';

export const GET_CANDIDATES_BY_ID = 'GET_CANDIDATES_BY_ID';
export const GET_CANDIDATES_BY_ID_SUCCESS = 'GET_CANDIDATES_BY_ID_SUCCESS';
export const GET_CANDIDATES_BY_ID_ERROR = 'GET_CANDIDATES_BY_ID_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_ERROR = 'GET_CATEGORY_BY_ID_ERROR';

export const DELETE_CATEGORY_BY_ID = 'DELETE_CATEGORY_BY_ID';
export const DELETE_CATEGORY_BY_ID_SUCCESS = 'DELETE_CATEGORY_BY_ID_SUCCESS';
export const DELETE_CATEGORY_BY_ID_ERROR = 'DELETE_CATEGORY_BY_ID_ERROR';

export const UPDATE_CATEGORY_BY_ID = 'UPDATE_CATEGORY_BY_ID';
export const UPDATE_CATEGORY_BY_ID_SUCCESS = 'UPDATE_CATEGORY_BY_ID_SUCCESS';
export const UPDATE_CATEGORY_BY_ID_ERROR = 'UPDATE_CATEGORY_BY_ID_ERROR';

export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES';
export const GET_SUB_CATEGORIES_SUCCESS = 'GET_SUB_CATEGORIES_SUCCESS';
export const GET_SUB_CATEGORIES_ERROR = 'GET_SUB_CATEGORIES_ERROR';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const CREATE_SUB_CATEGORY_SUCCESS = 'CREATE_SUB_CATEGORY_SUCCESS';
export const CREATE_SUB_CATEGORY_ERROR = 'CREATE_SUB_CATEGORY_ERROR';

export const GET_SUB_CATEGORY_BY_ID = 'GET_SUB_CATEGORY_BY_ID';
export const GET_SUB_CATEGORY_BY_ID_SUCCESS = 'GET_SUB_CATEGORY_BY_ID_SUCCESS';
export const GET_SUB_CATEGORY_BY_ID_ERROR = 'GET_SUB_CATEGORY_BY_ID_ERROR';

export const DELETE_SUB_CATEGORY_BY_ID = 'DELETE_SUB_CATEGORY_BY_ID';
export const DELETE_SUB_CATEGORY_BY_ID_SUCCESS = 'DELETE_SUB_CATEGORY_BY_ID_SUCCESS';
export const DELETE_SUB_CATEGORY_BY_ID_ERROR = 'DELETE_SUB_CATEGORY_BY_ID_ERROR';

export const UPDATE_SUB_CATEGORY_BY_ID = 'UPDATE_SUB_CATEGORY_BY_ID';
export const UPDATE_SUB_CATEGORY_BY_ID_SUCCESS = 'UPDATE_SUB_CATEGORY_BY_ID_SUCCESS';
export const UPDATE_SUB_CATEGORY_BY_ID_ERROR = 'UPDATE_SUB_CATEGORY_BY_ID_ERROR';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR';

export const GET_JOB_BY_ID = 'GET_JOB_BY_ID';
export const GET_JOB_BY_ID_SUCCESS = 'GET_JOB_BY_ID_SUCCESS';
export const GET_JOB_BY_ID_ERROR = 'GET_JOB_BY_ID_ERROR';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

// brand
export const GET_BRANDS = 'GET_BRANDS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_ERROR = 'GET_BRANDS_ERROR';

export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_ERROR = 'CREATE_BRAND_ERROR';

export const DELETE_BRAND_BY_ID = 'DELETE_BRAND_BY_ID';
export const DELETE_BRAND_BY_ID_SUCCESS = 'DELETE_BRAND_BY_ID_SUCCESS';
export const DELETE_BRAND_BY_ID_ERROR = 'DELETE_BRAND_BY_ID_ERROR';

export const UPDATE_BRAND_BY_ID = 'UPDATE_BRAND_BY_ID';
export const UPDATE_BRAND_BY_ID_SUCCESS = 'UPDATE_BRAND_BY_ID_SUCCESS';
export const UPDATE_BRAND_BY_ID_ERROR = 'UPDATE_BRAND_BY_ID_ERROR';

// product
// brand
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID';
export const DELETE_PRODUCT_BY_ID_SUCCESS = 'DELETE_PRODUCT_BY_ID_SUCCESS';
export const DELETE_PRODUCT_BY_ID_ERROR = 'DELETE_PRODUCT_BY_ID_ERROR';

export const UPDATE_PRODUCT_BY_ID = 'UPDATE_PRODUCT_BY_ID';
export const UPDATE_PRODUCT_BY_ID_SUCCESS = 'UPDATE_PRODUCT_BY_ID_SUCCESS';
export const UPDATE_PRODUCT_BY_ID_ERROR = 'UPDATE_PRODUCT_BY_ID_ERROR';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

// orders
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_ERROR = 'GET_ORDER_BY_ID_ERROR';

export const UPDATE_ORDER_BY_ID = 'UPDATE_ORDER_BY_ID';
export const UPDATE_ORDER_BY_ID_SUCCESS = 'UPDATE_ORDER_BY_ID_SUCCESS';
export const UPDATE_ORDER_BY_ID_ERROR = 'UPDATE_ORDER_BY_ID_ERROR';

export const GET_OFFERS = 'GET_OFFERS';
export const GET_OFFERS_ERROR = 'GET_OFFERS_ERROR';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';

export const GET_OFFER_BY_ID = 'GET_OFFER_BY_ID';
export const GET_OFFER_BY_ID_ERROR = 'GET_OFFER_BY_ID_ERROR';
export const GET_OFFER_BY_ID_SUCCESS = 'GET_OFFER_BY_ID_SUCCESS';

export const DELETE_OFFER_BY_ID = 'DELETE_OFFER_BY_ID';
export const DELETE_OFFER_BY_ID_ERROR = 'DELETE_OFFER_BY_ID_ERROR';
export const DELETE_OFFER_BY_ID_SUCCESS = 'DELETE_OFFER_BY_ID_SUCCESS';

export const CREATE_OFFER = 'CREATE_OFFER';
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
export const CREATE_OFFER_ERROR = 'CREATE_OFFER_ERROR';
