// theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

export const CHANGE_CATEGORY_MODAL_STATE = 'CHANGE_CATEGORY_MODAL_STATE';
export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY';

export const USER_LOGIN = 'USER_LOGIN';
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN';
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN';

export const USER_DETAILS = 'USER_DETAILS';
export const SUCCESS_USER_DETAILS = 'SUCCESS_USER_DETAILS';
export const ERROR_USER_DETAILS = 'ERROR_USER_DETAILS';

export const GET_CANDIDATES = 'GET_CANDIDATES';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_ERROR = 'GET_CANDIDATES_ERROR';

export const GET_CANDIDATES_BY_ID = 'GET_CANDIDATES_BY_ID';
export const GET_CANDIDATES_BY_ID_SUCCESS = 'GET_CANDIDATES_BY_ID_SUCCESS';
export const GET_CANDIDATES_BY_ID_ERROR = 'GET_CANDIDATES_BY_ID_ERROR';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_ERROR = 'GET_CATEGORY_BY_ID_ERROR';

export const DELETE_CATEGORY_BY_ID = 'DELETE_CATEGORY_BY_ID';
export const DELETE_CATEGORY_BY_ID_SUCCESS = 'DELETE_CATEGORY_BY_ID_SUCCESS';
export const DELETE_CATEGORY_BY_ID_ERROR = 'DELETE_CATEGORY_BY_ID_ERROR';

export const UPDATE_CATEGORY_BY_ID = 'UPDATE_CATEGORY_BY_ID';
export const UPDATE_CATEGORY_BY_ID_SUCCESS = 'UPDATE_CATEGORY_BY_ID_SUCCESS';
export const UPDATE_CATEGORY_BY_ID_ERROR = 'UPDATE_CATEGORY_BY_ID_ERROR';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR';

export const GET_JOB_BY_ID = 'GET_JOB_BY_ID';
export const GET_JOB_BY_ID_SUCCESS = 'GET_JOB_BY_ID_SUCCESS';
export const GET_JOB_BY_ID_ERROR = 'GET_JOB_BY_ID_ERROR';

export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';
